[package]
name = 'core-packages/console'
description = 'https://github.com/grilme99/CorePackages'
version = '1.2.3'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
Collections = 'core-packages/collections@1.2.3'
