[package]
name = 'core-packages/boolean'
description = 'https://github.com/js-for-lua/luau-polyfill'
version = '1.2.3'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
Number = 'core-packages/number@1.2.3'
