[package]
name = 'jsdotlua/symbol'
description = 'https://github.com/jsdotlua/luau-polyfill'
version = '1.0.0'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
